<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created' => 'Создано',
    'Content' => 'Содержание',
    'Email' => '',
    'Leave a comment' => 'Оставьте комментарий',
    'Modified' => 'Изменено',
    'Name' => 'Имя',
    'Reply' => 'Ответить',
    'Only authorized users can leave comments. Please {log-in} or pass a {registration}.' => 
        'Только зарегистрированные пользователи могут оставлять комментарии. Пожалуйста {log-in} или пройдите {registration}.',
    'Please enter your comment here' => 'Пожалуйста, введите ваш комментарий здесь',
    'Save' => 'Сохранить',
    'Status' => 'Статус',
    'Submit' => 'Отправить',
    'The requested model does not exist.' => 'Запрошенная модель не существует.',
    'Update' => 'Изменить',
    'Username' => 'Логин',
    'Your answer' => 'Ваш ответ',
    'log in' => 'войдите',
    'registration' => 'регистрацию',
];
